from pptx import Presentation
from pptx.util import Inches, Pt
import os

def create_presentation(output_path):
    prs = Presentation()
    
    # 1. Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = "GPU-Accelerated 3D Neurite Detection Pipeline"
    subtitle.text = "Automated Skeletonization and Proofreading\nGenerated by Samik Banerjee's Pipeline"
    
    # 2. Pipeline Overview
    bullet_slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(bullet_slide_layout)
    shapes = slide.shapes
    title_shape = shapes.title
    body_shape = shapes.placeholders[1]
    
    title_shape.text = "Pipeline Overview"
    tf = body_shape.text_frame
    tf.text = "An end-to-end processing pipeline for 3D volume imaging:"
    
    p = tf.add_paragraph()
    p.text = "1. GPU Neurite Detection: Isolate vessel-like structures."
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = "2. Soma Detection: Mask out dense cell bodies."
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = "3. SWC Skeletonization: Multi-threaded graph extraction and robust spline smoothing."
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = "4. Visualization: Interactive 3D rendering with Napari."
    p.level = 1
    
    # 3. Step 1: Neurite Detection
    slide = prs.slides.add_slide(bullet_slide_layout)
    shapes = slide.shapes
    title_shape = shapes.title
    body_shape = shapes.placeholders[1]
    
    title_shape.text = "Step 1: Neurite Detection"
    tf = body_shape.text_frame
    tf.text = "Script: process_neurites.py"
    
    p = tf.add_paragraph()
    p.text = "Applies a 3D Frangi Vesselness Filter."
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = "GPU-accelerated via CuPy for ultra-fast processing."
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = "Utilizes chunk-based memory management to prevent OOM errors on large volumes."
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = "Outputs: neurite_mask.tif"
    p.level = 1
    
    # 4. Step 2: Soma Detection
    slide = prs.slides.add_slide(bullet_slide_layout)
    shapes = slide.shapes
    title_shape = shapes.title
    body_shape = shapes.placeholders[1]
    
    title_shape.text = "Step 2: Soma Detection"
    tf = body_shape.text_frame
    tf.text = "Script: detect_somas.py"
    
    p = tf.add_paragraph()
    p.text = "Isolates large spherical cell bodies (somas) from the background."
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = "GPU-accelerated morphological operations (e.g. closing, thresholding)."
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = "Crucial for separating dense cell body clumps from delicate neurite branches."
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = "Outputs: soma_labels.tif"
    p.level = 1
    
    # 5. Step 3: Skeletonization
    slide = prs.slides.add_slide(bullet_slide_layout)
    shapes = slide.shapes
    title_shape = shapes.title
    body_shape = shapes.placeholders[1]
    
    title_shape.text = "Step 3: Skeletonization & Graph Extraction"
    tf = body_shape.text_frame
    tf.text = "Script: skeletonize_only.py"
    
    p = tf.add_paragraph()
    p.text = "Masks out soma regions to isolate pure neurite paths."
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = "Multi-threaded CPU skeletonization and graph extraction (sknw) over memory chunks."
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = "Filters isolated speckles (length < 10) and small terminal twigs (length < 30)."
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = "Robust spline smoothing: Heavily downsamples coordinates (1 pt per 4 voxels) and fits cubic splines to prevent Runge's phenomenon."
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = "Outputs: skeletons_smooth.swc (standard neuroscience format)"
    p.level = 1
    
    # 6. Step 4: 3D Visualization
    slide = prs.slides.add_slide(bullet_slide_layout)
    shapes = slide.shapes
    title_shape = shapes.title
    body_shape = shapes.placeholders[1]
    
    title_shape.text = "Step 4: 3D Visualization"
    tf = body_shape.text_frame
    tf.text = "Scripts: visualize_neurons_colored.py & visualize_mask.py"
    
    p = tf.add_paragraph()
    p.text = "Leverages Napari (VisPy) for interactive 3D rendering."
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = "Overlays SWC files as discrete, colored 3D paths representing individual graph components."
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = "Allows direct side-by-side overlay of raw volume, neurite mask, soma labels, and SWC skeletons for biological proofreading."
    p.level = 1
    
    prs.save(output_path)
    print(f"Presentation saved successfully to: {output_path}")

if __name__ == '__main__':
    output = "Pipeline_Overview.pptx"
    create_presentation(output)
