function all_centroids = detect_3d_cells_centroids()
    % DETECT_3D_CELLS_CENTROIDS Detects biological cell bodies with background subtraction and extracts centroids.
    % Divides the volume into 16 parts for memory efficiency.
    
    diary('run_diary.log');
    diary on;
    fprintf('Starting detect_3d_cells_centroids...\n');
    
    input_file = 'F0200_multichannel_cmle_ch04.tif';
    
    fprintf('Opening Tiff %s...\n', input_file);
    t = Tiff(input_file, 'r');
    h = t.getTag('ImageLength');
    w = t.getTag('ImageWidth');
    
    % count slices
    num_slices = 1;
    while not(t.lastDirectory())
        t.nextDirectory();
        num_slices = num_slices + 1;
    end
    t.setDirectory(1); % reset
    
    fprintf('Volume size: %d x %d x %d\n', w, h, num_slices);
    
    % Divide into 16 parts (4x4 in XY plane)
    num_blocks_x = 4;
    num_blocks_y = 4;
    
    block_w = ceil(w / num_blocks_x);
    block_h = ceil(h / num_blocks_y);
    
    margin = 50; % Margin to handle boundary effects
    
    all_centroids = [];
    
    % Vectorized block generation
    [X, Y] = meshgrid(1:num_blocks_x, 1:num_blocks_y);
    blocks = [X(:), Y(:)];
    
    for i = 1:size(blocks, 1)
        bx = blocks(i, 1);
        by = blocks(i, 2);
        
        fprintf('Processing block %d/%d (X:%d, Y:%d)...\n', i, size(blocks, 1), bx, by);
        
        % Core region
        x_start_core = (bx - 1) * block_w + 1;
        x_end_core = min(bx * block_w, w);
        y_start_core = (by - 1) * block_h + 1;
        y_end_core = min(by * block_h, h);
        
        % Region with margin
        x_start = max(1, x_start_core - margin);
        x_end = min(w, x_end_core + margin);
        y_start = max(1, y_start_core - margin);
        y_end = min(h, y_end_core + margin);
        
        % Load subvolume using Tiff (much faster than imread for large multi-page tiffs)
        fprintf('  Loading subvolume... ');
        tic;
        V = zeros(y_end - y_start + 1, x_end - x_start + 1, num_slices, 'uint16');
        for z = 1:num_slices
            t.setDirectory(z);
            slice = t.read();
            V(:,:,z) = slice(y_start:y_end, x_start:x_end);
        end
        t.setDirectory(1); % Reset for next block just in case, though we setDirectory inside loop anyway
        fprintf('Done in %.2f s.\n', toc);
        
        V = single(V);
        
        fprintf('  Applying Gaussian smoothing...\n');
        % Step 1: 3D Gaussian Smoothing
        V_smooth = imgaussfilt3(V, 15);
        
        fprintf('  Applying background subtraction...\n');
        % Step 2: Background Subtraction
        V_bg = imgaussfilt3(V, 40);
        V_sub = V_smooth - V_bg;
        V_sub(V_sub < 0) = 0; % Clamp negative values
        
        fprintf('  Thresholding and extracting centroids...\n');
        % Step 3: Thresholding to get Cell Morphology
        thresh = quantile(V_sub(:), 0.98); 
        cell_mask = V_sub > thresh;
        
        % Step 4: Extract Centroids
        CC = bwconncomp(cell_mask);
        stats = regionprops3(CC, 'Centroid', 'Volume');
        
        if isempty(stats)
            fprintf('  No components found.\n');
            continue;
        end
        
        valid_idx = stats.Volume >= 1;
        centroids = stats.Centroid(valid_idx, :);
        
        if isempty(centroids)
            fprintf('  No valid centroids found.\n');
            continue;
        end
        
        % Adjust centroid coordinates to global space
        global_centroids = centroids;
        global_centroids(:, 1) = global_centroids(:, 1) + x_start - 1;
        global_centroids(:, 2) = global_centroids(:, 2) + y_start - 1;
        
        % Filter centroids to keep only those within the core region
        valid_core = global_centroids(:, 1) >= x_start_core & ...
                     global_centroids(:, 1) <= x_end_core & ...
                     global_centroids(:, 2) >= y_start_core & ...
                     global_centroids(:, 2) <= y_end_core;
                     
        global_centroids = global_centroids(valid_core, :);
        fprintf('  Found %d valid centroids in core.\n', size(global_centroids, 1));
        
        if ~isempty(global_centroids)
            all_centroids = [all_centroids; global_centroids];
        end
    end
    t.close();
    
    fprintf('Total detected cell candidates: %d\n', size(all_centroids, 1));
    
    % Output SWC file
    swc_filename = 'centroids.swc';
    fprintf('Saving centroids to %s...\n', swc_filename);
    fid = fopen(swc_filename, 'w');
    fprintf(fid, '# SWC file generated by detect_3d_cells_centroids.m\n');
    fprintf(fid, '# id type x y z radius parent\n');
    
    num_centroids = size(all_centroids, 1);
    
    if num_centroids > 0
        swc_data = zeros(num_centroids, 7);
        swc_data(:, 1) = 1:num_centroids;
        swc_data(:, 2) = 2; % type 2 = soma/cell body
        swc_data(:, 3:5) = all_centroids;
        swc_data(:, 6) = 1.0; % radius
        swc_data(:, 7) = -1; % parent
        
        fprintf(fid, '%d %d %.3f %.3f %.3f %.1f %d\n', swc_data');
    end
    
    fclose(fid);
    
    save('all_centroids.mat', 'all_centroids');
    fprintf('Done.\n');
end
