import tifffile
import numpy as np
import scipy.ndimage as ndi
from skimage.measure import regionprops, label
import time
import os
import argparse


def process_volume(input_file=None, output_file=None):
    if input_file is None:
        input_file = 'F0200_multichannel_cmle_ch03.tif'
        if not os.path.exists(input_file):
            input_file = os.path.join('..', input_file)
    
    if output_file is None:
        output_file = 'centroids_FP.swc'
        
    if not os.path.exists(input_file):
        print(f"Error: File {input_file} not found.")
        return

    print(f"Opening FP channel Tiff {input_file}...")
    
    with tifffile.TiffFile(input_file) as tif:
        pages = tif.pages
        num_slices = len(pages)
        shape = pages[0].shape
        h, w = shape[0], shape[1]
        
        print(f"Volume size: {w} x {h} x {num_slices}")
        
        num_blocks_x = 4
        num_blocks_y = 4
        block_w = int(np.ceil(w / num_blocks_x))
        block_h = int(np.ceil(h / num_blocks_y))
        margin = 50
        
        all_centroids = []
        
        for by in range(num_blocks_y):
            for bx in range(num_blocks_x):
                print(f"\nProcessing block X:{bx+1}, Y:{by+1}...")
                
                # Core region
                x_start_core = bx * block_w
                x_end_core = min((bx + 1) * block_w, w)
                y_start_core = by * block_h
                y_end_core = min((by + 1) * block_h, h)
                
                # Region with margin
                x_start = max(0, x_start_core - margin)
                x_end = min(w, x_end_core + margin)
                y_start = max(0, y_start_core - margin)
                y_end = min(h, y_end_core + margin)
                
                print("  Loading subvolume...")
                t0 = time.time()
                V = np.zeros((y_end - y_start, x_end - x_start, num_slices), dtype=np.float32)
                for z in range(num_slices):
                    page = pages[z].asarray()
                    V[:, :, z] = page[y_start:y_end, x_start:x_end]
                print(f"  Loaded in {time.time()-t0:.2f} s")
                
                print("  Applying Gaussian smoothing...")
                V_smooth = ndi.gaussian_filter(V, sigma=15)
                
                print("  Applying background subtraction...")
                V_bg = ndi.gaussian_filter(V, sigma=40)
                V_sub = V_smooth - V_bg
                V_sub[V_sub < 0] = 0
                
                print("  Thresholding and extracting centroids...")
                thresh = np.percentile(V_sub, 98)
                cell_mask = V_sub > thresh
                
                labeled_mask, num_features = ndi.label(cell_mask)
                if num_features == 0:
                    print("  No components found.")
                    continue
                
                props = regionprops(labeled_mask)
                centroids = []
                for p in props:
                    if p.area >= 1:
                        centroids.append(p.centroid) # returns (y, x, z)
                
                if not centroids:
                    print("  No valid centroids found.")
                    continue
                
                centroids = np.array(centroids)
                
                # Adjust centroid coordinates to global space (X, Y, Z) order
                global_centroids = np.zeros_like(centroids)
                global_centroids[:, 0] = centroids[:, 1] + x_start # X
                global_centroids[:, 1] = centroids[:, 0] + y_start # Y
                global_centroids[:, 2] = centroids[:, 2] # Z
                
                # Filter centroids to keep only those within the core region
                valid_core = (global_centroids[:, 0] >= x_start_core) & \
                             (global_centroids[:, 0] < x_end_core) & \
                             (global_centroids[:, 1] >= y_start_core) & \
                             (global_centroids[:, 1] < y_end_core)
                             
                global_centroids = global_centroids[valid_core]
                print(f"  Found {len(global_centroids)} valid centroids in core.")
                
                if len(global_centroids) > 0:
                    all_centroids.extend(global_centroids)
                    
        print(f"\nTotal detected cell candidates (FP): {len(all_centroids)}")
        
        swc_filename = output_file
        print(f"Saving centroids to {swc_filename}...")
        with open(swc_filename, 'w') as f:
            f.write("# SWC file generated by python vectorized script\n")
            f.write("# id type x y z radius parent\n")
            for i, c in enumerate(all_centroids):
                f.write(f"{i+1} 2 {c[0]:.3f} {c[1]:.3f} {c[2]:.3f} 1.0 -1\n")
        print("Done.")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Detect 3D cell centroids in FP TIFF volume.')
    parser.add_argument('--input', type=str, help='Path to the input TIFF file')
    parser.add_argument('--output', type=str, help='Path to the output SWC file')
    args = parser.parse_args()
    
    process_volume(input_file=args.input, output_file=args.output)
