import tifffile
import numpy as np
import scipy.ndimage as ndi
from skimage.measure import regionprops
from scipy.spatial import KDTree
import time
import os
import argparse
import pandas as pd
from concurrent.futures import ProcessPoolExecutor, as_completed

def process_block(args):
    """Function to process a single block, designed for parallel execution."""
    bx, by, block_w, block_h, w, h, num_slices, margin, input_file, min_area = args
    
    # Core region
    x_start_core, x_end_core = bx * block_w, min((bx + 1) * block_w, w)
    y_start_core, y_end_core = by * block_h, min((by + 1) * block_h, h)
    
    # Region with margin
    x_start, x_end = max(0, x_start_core - margin), min(w, x_end_core + margin)
    y_start, y_end = max(0, y_start_core - margin), min(h, y_end_core + margin)
    
    # We must open the file inside each process to avoid sharing the file handle
    # This might be slightly slower but safer
    with tifffile.TiffFile(input_file) as tif:
        pages = tif.pages
        V = np.zeros((y_end - y_start, x_end - x_start, num_slices), dtype=np.float32)
        for z in range(num_slices):
            V[:, :, z] = pages[z].asarray()[y_start:y_end, x_start:x_end]
    
    V_smooth = ndi.gaussian_filter(V, sigma=15)
    V_bg = ndi.gaussian_filter(V, sigma=40)
    V_sub = np.maximum(V_smooth - V_bg, 0)
    
    thresh = np.percentile(V_sub, 98)
    labeled_mask, num_features = ndi.label(V_sub > thresh)
    
    block_centroids = []
    if num_features > 0:
        props = regionprops(labeled_mask)
        for p in props:
            if p.area >= min_area:
                cy, cx, cz = p.centroid
                gx, gy, gz = cx + x_start, cy + y_start, cz
                
                # Core check to avoid duplicates from overlapping margins
                if x_start_core <= gx < x_end_core and y_start_core <= gy < y_end_core:
                    block_centroids.append([gx, gy, gz])
    
    return block_centroids

def detect_centroids_parallel(input_file, min_area=1, max_workers=4):
    """Parallelized detection using a process pool."""
    if not os.path.exists(input_file):
        input_file_fallback = os.path.join('..', input_file)
        if os.path.exists(input_file_fallback):
            input_file = input_file_fallback
        else:
            raise FileNotFoundError(f"File {input_file} not found.")

    print(f"Opening volume: {input_file} for parallel detection (workers={max_workers})...")
    with tifffile.TiffFile(input_file) as tif:
        num_slices = len(tif.pages)
        h, w = tif.pages[0].shape
    
    num_blocks_x, num_blocks_y = 4, 4
    block_w, block_h = int(np.ceil(w / num_blocks_x)), int(np.ceil(h / num_blocks_y))
    margin = 50
    
    # Prepare arguments for each block
    tasks = []
    for by in range(num_blocks_y):
        for bx in range(num_blocks_x):
            tasks.append((bx, by, block_w, block_h, w, h, num_slices, margin, input_file, min_area))
    
    all_centroids = []
    with ProcessPoolExecutor(max_workers=max_workers) as executor:
        futures = [executor.submit(process_block, task) for task in tasks]
        for i, future in enumerate(as_completed(futures)):
            result = future.result()
            all_centroids.extend(result)
            print(f"  Finished block {i+1}/16")
            
    return np.array(all_centroids)

def save_swc(centroids, filename, comment=""):
    if centroids is None or len(centroids) == 0:
        with open(filename, 'w') as f:
            f.write(f"# SWC file generated by parallel pipeline. {comment}\n")
        return
    with open(filename, 'w') as f:
        f.write(f"# SWC file generated by parallel pipeline. {comment}\n")
        f.write("# id type x y z radius parent\n")
        for i, c in enumerate(centroids):
            f.write(f"{i+1} 2 {c[0]:.3f} {c[1]:.3f} {c[2]:.3f} 1.0 -1\n")

def save_scaled_swc(centroids, filename, scale_factors):
    if centroids is None or len(centroids) == 0: return
    sx, sy, sz = scale_factors
    scaled = centroids * np.array([sx, sy, sz])
    with open(filename, 'w') as f:
        f.write(f"# Scaled SWC file.\n")
        for i, c in enumerate(scaled):
            f.write(f"{i+1} 2 {c[0]:.6f} {c[1]:.6f} {c[2]:.6f} 1.0 -1\n")

def main():
    parser = argparse.ArgumentParser(description='Parallel dual-channel detection.')
    parser.add_argument('--dapi', type=str, default='F0200_multichannel_cmle_ch04.tif')
    parser.add_argument('--fp', type=str, default='F0200_multichannel_cmle_ch03.tif')
    parser.add_argument('--workers', type=int, default=4, help='Number of parallel processes')
    parser.add_argument('--dist_thresh', type=float, default=120.0)
    args = parser.parse_args()

    t_start = time.time()
    scales = (0.1102, 0.1102, 0.5)

    print("\n--- Phase 1: Parallel DAPI Detection ---")
    c_dapi = detect_centroids_parallel(args.dapi, min_area=1, max_workers=args.workers)
    save_swc(c_dapi, 'centroids_DAPI.swc')
    save_scaled_swc(c_dapi, 'centroids_DAPI_scaled.swc', scales)

    print("\n--- Phase 2: Parallel FP Detection ---")
    c_fp = detect_centroids_parallel(args.fp, min_area=40, max_workers=args.workers)
    save_swc(c_fp, 'centroids_FP.swc')
    save_scaled_swc(c_fp, 'centroids_FP_scaled.swc', scales)

    print("\n--- Phase 3: Spatial Filtering ---")
    if len(c_fp) > 0 and len(c_dapi) > 0:
        dapi_tree = KDTree(c_dapi)
        distances, _ = dapi_tree.query(c_fp, k=1)
        c_fp_final = c_fp[distances <= args.dist_thresh]
        print(f"Filtered {len(c_fp)} down to {len(c_fp_final)}")
        save_swc(c_fp_final, 'centroids_FP_final.swc')
        save_scaled_swc(c_fp_final, 'centroids_FP_final_scaled.swc', scales)

    print(f"\nParallel pipeline completed in {time.time() - t_start:.2f}s")

if __name__ == '__main__':
    main()
