import numpy as np
from scipy.spatial import KDTree
import time
import os
import argparse
import pandas as pd

# Import specialized detection functions
import run_centroids_DAPI
import run_centroids_FP

def load_swc(filename):
    """Loads centroids from an SWC file into a numpy array (x, y, z)."""
    if not os.path.exists(filename):
        return None
    try:
        # SWC format: id type x y z radius parent
        data = pd.read_csv(filename, sep=' ', comment='#', header=None, 
                          names=['id', 'type', 'x', 'y', 'z', 'r', 'p'])
        return data[['x', 'y', 'z']].values
    except Exception as e:
        print(f"Error loading SWC {filename}: {e}")
        return None

def save_swc(centroids, filename, comment=""):
    """Saves centroids to an SWC file."""
    if centroids is None or len(centroids) == 0:
        # Create empty SWC
        with open(filename, 'w') as f:
            f.write(f"# SWC file generated by pipeline. {comment}\n")
            f.write("# id type x y z radius parent\n")
        print(f"No centroids to save to {filename}")
        return

    with open(filename, 'w') as f:
        f.write(f"# SWC file generated by pipeline. {comment}\n")
        f.write("# id type x y z radius parent\n")
        for i, c in enumerate(centroids):
            f.write(f"{i+1} 2 {c[0]:.3f} {c[1]:.3f} {c[2]:.3f} 1.0 -1\n")
    print(f"Saved {len(centroids)} centroids to {filename}")

def main():
    parser = argparse.ArgumentParser(description='Run dual-channel cell detection with spatial filtering.')
    parser.add_argument('--dapi', type=str, default='F0200_multichannel_cmle_ch04.tif', help='Path to DAPI TIFF')
    parser.add_argument('--fp', type=str, default='F0200_multichannel_cmle_ch03.tif', help='Path to FP TIFF')
    parser.add_argument('--output_dapi', type=str, default='centroids_DAPI.swc', help='Output DAPI SWC')
    parser.add_argument('--output_fp', type=str, default='centroids_FP.swc', help='Output raw FP SWC')
    parser.add_argument('--output_final', type=str, default='centroids_FP_final.swc', help='Output filtered FP SWC')
    parser.add_argument('--dist_thresh', type=float, default=10.0, help='Proximity threshold in pixels')
    parser.add_argument('--force', action='store_true', help='Force re-detection even if SWC files exist')
    args = parser.parse_args()

    t_start = time.time()

    # 1. Handle DAPI centroids
    print("\n--- Phase 1: DAPI Channel ---")
    if not args.force and os.path.exists(args.output_dapi):
        print(f"Found existing DAPI centroids at {args.output_dapi}. Skipping detection.")
        centroids_dapi = load_swc(args.output_dapi)
    else:
        print(f"Detecting DAPI centroids from {args.dapi}...")
        centroids_dapi = run_centroids_DAPI.process_volume(input_file=args.dapi, output_file=args.output_dapi)

    # 2. Handle FP centroids
    print("\n--- Phase 2: FP Channel ---")
    if not args.force and os.path.exists(args.output_fp):
        print(f"Found existing FP centroids at {args.output_fp}. Skipping detection.")
        centroids_fp = load_swc(args.output_fp)
    else:
        print(f"Detecting FP centroids from {args.fp}...")
        centroids_fp = run_centroids_FP.process_volume(input_file=args.fp, output_file=args.output_fp)

    # 3. Filter FP centroids based on DAPI proximity
    print(f"\n--- Phase 3: Spatial Filtering (Proximity <= {args.dist_thresh}px) ---")
    if centroids_fp is not None and len(centroids_fp) > 0 and centroids_dapi is not None and len(centroids_dapi) > 0:
        dapi_tree = KDTree(centroids_dapi)
        distances, indices = dapi_tree.query(centroids_fp, k=1)
        
        valid_mask = distances <= args.dist_thresh
        centroids_fp_final = centroids_fp[valid_mask]
        
        print(f"Filtered {len(centroids_fp)} FP centroids down to {len(centroids_fp_final)} based on DAPI proximity.")
    else:
        centroids_fp_final = np.array([])
        print("Warning: One or both channels produced no detections or returned None. Final output will be empty.")

    # 4. Save final result
    save_swc(centroids_fp_final, args.output_final, f"Spatial filter vs {args.output_dapi} at {args.dist_thresh}px")

    print(f"\nPipeline completed in {time.time() - t_start:.2f} seconds.")

if __name__ == '__main__':
    main()
